version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: blps_db
      POSTGRES_USER: blps_user
      POSTGRES_PASSWORD: blps_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blps_user -d blps_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  activemq:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

  main-app:
    build: ./main
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_started
    environment:
      SPRING_JPA_PROPERTIES_HIBERNATE_TRANSACTION_JTA_PLATFORM: com.atomikos.icatch.jta.hibernate4.AtomikosPlatform
      SPRING_DATASOURCE_XA_SERVER_NAME: postgres
      SPRING_DATASOURCE_XA_DATABASE_NAME: blps_db
      SPRING_DATASOURCE_XA_USER: blps_user
      SPRING_DATASOURCE_XA_PASSWORD: blps_password
      SPRING_DATASOURCE_XA_PORT: "5432"
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
    ports:
      - "8080:8080"

  mail-service:
    build: ./mail
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_started
    environment:
      MAIL_USERNAME: name
      MAIL_PASSWORD: pass
      MAIL_BOX: mail
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
    ports:
      - "8081:8081"

volumes:
  postgres_data:
