spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true

messaging:
  queue:
    name: delivery.status.queue

server:
  port: 8080
